services:
  clan-points-bot:
    build:
      context: ./clan-points-bot
      dockerfile: Dockerfile
    volumes:
      - ./clan-points-bot:/bot:ro
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             watchmedo auto-restart --directory=/bot --pattern=*.py --recursive -- python /bot/bot.py"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
  
  member-processor:
    build:
      context: ./member-processor
      dockerfile: Dockerfile
    volumes:
      - ./member-processor:/app:ro
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- python /app/app.py"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongodb_data: