services:
  app:
    build:
      context: ./clan-points-bot
      dockerfile: Dockerfile
    volumes:
      - ./clan-points-bot:/bot
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             watchmedo auto-restart --directory=/bot --pattern=*.py --recursive -- python /bot/bot.py"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: