class Tasks:
    AVAILABLE_TASKS = [
        {
            "task_id": 0,
            "name": "Legacy Points",
            "points_awarded": 0,
            "cooldown_days": 0,
            "submittable": False,
            "repeatable": False,
        },
        {
            "task_id": 1,
            "name": "Month in Clan",
            "points_awarded": 2,
            "cooldown_days": 0,
            "submittable": False,
            "repeatable": True,
        },
        {
            "task_id": 2,
            "name": "Donating 50m to Clan Coffer (single donation)",
            "points_awarded": 1,
            "cooldown_days": 0,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 3,
            "name": "Coming in 1st Place in a Non-Bingo Competition",
            "points_awarded": 3,
            "cooldown_days": 0,
            "submittable": False,
            "repeatable": True,
        },
        {
            "task_id": 4,
            "name": "Coming in 1st Place in a Bingo",
            "points_awarded": 4,
            "cooldown_days": 0,
            "submittable": False,
            "repeatable": True,
        },
        {
            "task_id": 7,
            "name": "Splitting a 10m+ value item with clanmates",
            "points_awarded": 1,
            "cooldown_days": 0,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 8,
            "name": "Joining a casual event (i.e Callisto mass; Clan X-mas Drop Party)",
            "points_awarded": 1,
            "cooldown_days": 0,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 9,
            "name": "Joining a competion (SOW, BOW, Bingo)",
            "points_awarded": 1,
            "cooldown_days": 0,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 10,
            "name": "Bumping a kitty form",
            "points_awarded": 1,
            "cooldown_days": 10,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 11,
            "name": "Helping with GM or Master combat achievement: no task repeats",
            "points_awarded": 1,
            "cooldown_days": 1,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 12,
            "name": "Mentoring someone through their 1st raid, inferno, or quiver",
            "points_awarded": 1,
            "cooldown_days": 1,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 13,
            "name": "Posting a picture of your IRL pet in floofs",
            "points_awarded": 1,
            "cooldown_days": 7,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 14,
            "name": "Recruiting someone to the clan",
            "points_awarded": 1,
            "cooldown_days": 1,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 15,
            "name": "Helping host an event (no rank restriction)",
            "points_awarded": 1,
            "cooldown_days": 1,
            "submittable": True,
            "repeatable": True,
        },
        {
            "task_id": 16,
            "name": "Server boosting",
            "points_awarded": 1,
            "cooldown_days": 1,
            "submittable": True,
            "repeatable": False,
        }
    ]